import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/server/layout/Header";
import Sidebar from "../components/server/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="flex h-screen bg-background text-gray-600 overflow-hidden">
        <Sidebar />
        <div className="flex flex-col flex-1 ml-4 mr-6">
          <Header />
          <div className="overflow-hidden flex-grow">{children}</div>
        </div>
      </div>
    </div>
  );
}
